FROM ubuntu:24.04
# FROM debian:bookworm-slim

ARG PYENV_PATH="/opt/venv"
ARG CODE_PATH="/opt/webapp"
ARG STATIC_PATH="/opt/static"
ARG MEDIA_PATH="/opt/media"

RUN mkdir ${CODE_PATH}
RUN mkdir ${STATIC_PATH}
RUN mkdir ${MEDIA_PATH}

VOLUME ${CODE_PATH}
VOLUME ${STATIC_PATH}
VOLUME ${MEDIA_PATH}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-venv \
        && rm -rf /var/lib/apt/lists/*

# Create virtual environment
RUN python3 -m venv ${PYENV_PATH}

# Activate the virtual environment (important for subsequent commands)
ENV VIRTUAL_ENV=${PYENV_PATH}
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN rm requirements.txt

# Expose the port
EXPOSE 8000

# Set the working directory
WORKDIR /opt/webapp

# Command to run when the container starts
# Example:
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "your_app:app"] 
# Or for a simple test:
# CMD ["/opt/venv/bin/python", "-c", "print('Hello from your container!')"]